PB-974: separate test files for opentransapi and stationboard
Originally there were separate test files for opentransapi and the stationboard.
This is now again the case, also several test cases got lost, which were re-added
again.
Also added dependencies in order to fix
 TypeError: __init__() got an unexpected keyword argument 'management'